stages:
  - build
 
compile:
  stage: build
  tags:
    - windows
  script:
    - cd .\\examples\\modbus\\sunrise_modbus_continuous
    - arduino-cli --config-file c:\\Users\\utvlab\\AppData\\Local\\Arduino15\\arduino-cli.yaml compile  --fqbn arduino:avr:mega -o ignored0.bin sunrise_modbus_continuous.ino
