stages:
  - build
 
compile:
  stage: build
  tags:
    - windows
  script:
    - cd .\\examples\\modbus\\sunrise_modbus_continuous
    - arduino-cli compile  --fqbn arduino:avr:mega -o ignored0.bin sunrise_modbus_continuous.ino
