image: ubuntu:18.04
 
before_script:
  - apt-get update
  - cd ~
  - apt-get install curl -y
  - curl -L -o arduino-cli.tar.bz2 https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2
  - tar xjf arduino-cli.tar.bz2
  - rm arduino-cli.tar.bz2
  - mv `ls -1` /usr/bin/arduino-cli
 
stages:
  - build
 
compile:
  stage: build
  script:
    - arduino-cli compile -o ignored0.bin ./sunrise-examples-arduino/examples/modbus/sunrise_modbus_continuous/sunrise_modbus_continuous.ino
